// @ts-check
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window["go"]["backend"]["FilesStorage"]["GetAll"]();
}

export function GetItem(arg1) {
  return window["go"]["backend"]["FilesStorage"]["GetItem"](arg1);
}

export function RemoveItem(arg1) {
  return window["go"]["backend"]["FilesStorage"]["RemoveItem"](arg1);
}

export function SetAll(arg1) {
  return window["go"]["backend"]["FilesStorage"]["SetAll"](arg1);
}

export function SetItem(arg1, arg2) {
  return window["go"]["backend"]["FilesStorage"]["SetItem"](arg1, arg2);
}
