// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { backend } from "../models";

export function GetItem(arg1: string): Promise<backend.StringRef>;

export function RemoveItem(arg1: string): Promise<void>;

export function SetItem(arg1: string, arg2: string): Promise<void>;
