// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as helpers$0 from "../helpers/models.js";

export interface Record {
  key: string;
  blob64: helpers$0.Blob64;
  options: string;
}

export interface WebFileRef {
  $$id: string;
  $$blob64: helpers$0.Blob64;
  name: string;
  size: number;
}
