export { ReactComponent as AppendRow } from "./AppendRow.svg";
export { ReactComponent as Cross } from "./Cross.svg";
export { ReactComponent as DeleteRow } from "./DeleteRow.svg";
export { ReactComponent as DirOpen } from "./DirOpen.svg";
export { ReactComponent as Download } from "./Download.svg";
export { ReactComponent as FileBlank } from "./FileBlank.svg";
export { ReactComponent as InsertRow } from "./InsertRow.svg";
export { ReactComponent as Trash } from "./Trash.svg";
export { ReactComponent as Upload } from "./Upload.svg";
