// @ts-check
// This file is automatically generated. DO NOT EDIT

export function GetItem(arg1) {
  return window["go"]["backend"]["ConfigStorage"]["GetItem"](arg1);
}

export function RemoveItem(arg1) {
  return window["go"]["backend"]["ConfigStorage"]["RemoveItem"](arg1);
}

export function SetItem(arg1, arg2) {
  return window["go"]["backend"]["ConfigStorage"]["SetItem"](arg1, arg2);
}
