const {
  REACT_APP_NAME: APP_NAME = "sp-ed",
  REACT_APP_VERSION: APP_VERSION,
  REACT_APP_REPO_URL: REPO_URL,
  REACT_APP_BUGS_URL: BUGS_URL,
} = process.env;

export { APP_NAME, APP_VERSION, REPO_URL, BUGS_URL };
