// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetItem(
  key: string,
): $CancellablePromise<$models.StringRef | null> {
  return $Call.ByID(1060918307, key);
}

export function RemoveItem(key: string): $CancellablePromise<void> {
  return $Call.ByID(4090001799, key);
}

export function SetItem(key: string, value: string): $CancellablePromise<void> {
  return $Call.ByID(3440142159, key, value);
}
