// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as files$0 from "../files/models.js";

export function GetAll(): $CancellablePromise<
  { [_ in string]?: files$0.Record | null } | null
> {
  return $Call.ByID(3487456056);
}

export function GetItem(
  key: string,
): $CancellablePromise<files$0.Record | null> {
  return $Call.ByID(800697722, key);
}

export function RemoveItem(key: string): $CancellablePromise<void> {
  return $Call.ByID(984448924, key);
}

export function SetAll(
  all: { [_ in string]?: files$0.Record | null } | null,
): $CancellablePromise<void> {
  return $Call.ByID(3458027036, all);
}

export function SetItem(
  key: string,
  value: files$0.Record | null,
): $CancellablePromise<void> {
  return $Call.ByID(3155842350, key, value);
}
