// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as files$0 from "../files/models.js";

export interface StringRef {
  value: string;
}

export type WebFileRef = files$0.WebFileRef;
