// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./internal/backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as helpers$0 from "./internal/helpers/models.js";

export function CreateFile(
  key: string,
  baseFileName: string,
): $CancellablePromise<string> {
  return $Call.ByID(3418645411, key, baseFileName);
}

export function GetAppInfo(): $CancellablePromise<string> {
  return $Call.ByID(713661858);
}

export function OpenFile(
  multiple: boolean,
): $CancellablePromise<(backend$0.WebFileRef | null)[] | null> {
  return $Call.ByID(1958968983, multiple);
}

export function SaveFileAs(
  blob64: helpers$0.Blob64,
  baseFileName: string,
): $CancellablePromise<void> {
  return $Call.ByID(2627549058, blob64, baseFileName);
}

export function SetIsDirty(isDirty: boolean): $CancellablePromise<void> {
  return $Call.ByID(4220956037, isDirty);
}
