// This file is automatically generated. DO NOT EDIT
import { files } from "../models";

export function CreateFile(arg1: string, arg2: string): Promise<string>;

export function GetAppInfo(): Promise<string>;

export function OpenFile(arg1: boolean): Promise<Array<files.WebFileRef>>;

export function SaveFileAs(arg1: string, arg2: string): Promise<void>;

export function SetIsDirty(arg1: boolean): Promise<void>;
